### PR TITLE
Use getApolloState instead relying on reduxRootKey

### PR DESCRIPTION
**Pull request by sheerun**
I hope I got it well. It may or may not require major bump.

I'd be really glad if you released it asap, as I use my own redux store.

### CODE REVIEW

**Comment by sheerun** [comment]
This is simpler and more accurate implementation of #223, should resolve #221

**Comment by sheerun** [comment]
Actually it shoudn't require major bump as queryManager.getApolloState() was available in previous versions.

**Comment by stubailo** [comment]
I'm a little uncomfortable because this isn't strictly a "public API" but it definitely works for now! We'll just need to be careful to not remove that function, or rename `queryManager`.

**Comment by sheerun** [comment]
CI fails for non-related reasons.. I guess if you figure out public API for getting apollo state, you can change it. At least it's less hacky than manually fetching it by `reduxRootSelector` (that can be both string or function..)

**Comment by stubailo** [comment]
Yeah I think this is a great solution right now, let's do it!

**Comment by sheerun** [comment]
@stubailo Any chance to release it soon? :)

**Comment by jbaxleyiii** [comment]
@sheerun I'll get this out today!

**Pull request merged**
