### PR TITLE
Update React and Combine Tests

### PR DESCRIPTION
**Pull request by johnthepink**
This updates react to 15.4.1, and react-native to 0.38.0. React 15.4 fixed the `injectEnvironment` issue mentioned [here](https://github.com/facebook/react/issues/7386), which prevented our tests from using enzyme and react-test-renderer in the same file.

### CODE REVIEW

**Comment by johnthepink** [comment]
Ran in to an interesting issue, any suggestions more than welcome.

Upgrading React introduced an issue on the CI with importing "React" vs "react". See [this comment](https://github.com/facebook/jest/issues/1840#issuecomment-263004102).

Using the jest preset included in react-native actually fixed this issue, but caused tests to fail that were making actual network requests (see server swapi test).

For now, I have downgraded to react 15.4.0. Moving forward, we should see if we can fix the network request tests, as the react-native jest preset included in react-native cleans up a lot of test logs.

**Comment by stubailo** [comment]
Looks great! Perhaps let's open an issue for the other thing and merge this PR?

**Comment by jbaxleyiii** [comment]
@johnthepink thanks so much for doing this! It may be worth setting up greenkeeper for this repo. @stubailo is that something someone at MDG could do?

**Comment by johnthepink** [comment]
@jbaxleyiii @stubailo creating an issue now.

**Pull request merged**
