### PR TITLE
add react-dom as peer depency

### PR DESCRIPTION
**Pull request by koenpunt**
TODO:

- [ ] If this PR is a new feature, reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests
- [ ] Rebase your changes on master so that they can be merged easily
- [ ] Make sure all tests and linter rules pass
- [x] Update CHANGELOG.md with your change
- [ ] If this was a change that affects the external API, update the docs and post a link to the PR in the discussion

### CODE REVIEW

**Comment by helfer** [comment]
@koenpunt if I'm not mistaken people could use react-apollo anywhere they like, not only in the browser, so I'm not sure why we should add react-dom as a peer dependency?

**Comment by koenpunt** [comment]
> since React 15.4 react-dom is no longer "secretly" included.
>
> ref: https://github.com/facebook/react/releases/tag/v15.4.0

And since `react-dom/server` is required from [`server.ts`](https://github.com/apollostack/react-apollo/blob/master/src/server.ts#L3), this causes errors.

**Comment by helfer** [comment]
Ah, I did not see that, thanks!

Can you sign the CLA?

**Comment by migueloller** [comment]
What will this PR mean for using `react-apollo` in React Native? Will you need to install `react-dom` as a dependency to prevent NPM from complaining?

**Comment by koenpunt** [comment]
> What will this PR mean for using react-apollo in React Native?

I am using `react-apollo` with React Native, and building fails without adding `react-dom` as a dependency due to the before mentioned [require](https://github.com/apollostack/react-apollo/blob/master/src/server.ts#L3)

**Comment by migueloller** [comment]
Having to install `react-dom` as a dependency when using React Native isn't good though.

**Comment by helfer** [comment]
@migueloller don't you effectively already have to do that now if you use SSR? Or is SSR not a thing in react-native?

Since we only use `renderToString`, we could potentially use a pared down react-dom package if such a thing exists.

**Comment by migueloller** [comment]
@helfer,

SSR is not a thing in React Native. The React team keeps the core React library separate from the different renderers (native, DOM/SSR, ART, etc.) so it might make sense to separate DOM/SSR logic from Apollo into a different package.

Perhaps there could be a pared down `renderToString` out there somewhere that doesn't include all of the shadow DOM diffing logic that `ReactDOM.render` needs and simply traverses the component tree and renders it. I haven't come across it though.

**Comment by jbaxleyiii** [comment]
@migueloller we have discussed moving the main logic of this renderer out of this package. For now, I think we should merge this. Up until 15.4 RN builds got react-dom anyway.

I think in a future release we should remove the react-dom integration for a new package or just remove the render to string part. This would also allow this library to potentially be used with react-like renderers (i.e inferno and preact)

**Comment by jbaxleyiii** [comment]
@koenpunt could you update the changelog?

**Comment by koenpunt** [comment]
@jbaxleyiii done.

**Comment by jbaxleyiii** [comment]
@koenpunt sorry this took so long to merge!

**Pull request merged**
