### PR TITLE
Use instance.fetchData rather than a static method.

### PR DESCRIPTION
**Pull request by tmeasday**
Fixes issue with Redux's `connect` hoisting `fetchData` statically.

See #350

### CODE REVIEW

**Comment by tmeasday** [comment]
Mind taking a look @jbaxleyiii

**Comment by tmeasday** [comment]
Not quite sure what you mean but I've added a changelog entry. Will bump and release when you are good to merge.

**Comment by jbaxleyiii** [comment]
@tmeasday looks great! Feel free to release as you want!

**Comment by tmeasday** [comment]
I'd like to sort out https://github.com/apollostack/react-apollo/pull/357 before releasing

**Comment by jbaxleyiii** [comment]
I'll take a look!

**Pull request merged**
