### PR TITLE
Expose updateQuery

### PR DESCRIPTION
**Pull request by joarwilk**
Connected to https://github.com/apollostack/apollo-client/pull/506

### CODE REVIEW

**Comment by joarwilk** [comment]
Actually, this wont work. What's the preferred way of doing query updates when we're getting data updates from the side (as in from a websocket feed)?

**Comment by jbaxleyiii** [comment]
@joarwilk thanks for this! Could you add a usage test as well?

**Comment by joarwilk** [comment]
@jbaxleyiii Done. Do note it will break however. The `updateQuery` method was supposed to be a part of apollo client 0.4.11 but it didn't make it somehow. This can't be merged until the next client release.

I'm not sure how you guys handle breaking changes but I guess this would have to wait until the next minor (?) `react-apollo` version goes out since it depends on a newer client version.

**Comment by jbaxleyiii** [comment]
@joarwilk could you rebase this? I'd love to get it merged and out for release!

**Comment by jbaxleyiii** [comment]
I pulled this into #152 so I could go ahead and release it!

**Pull request closed without merging**
