### PR TITLE
Upgrade Dev Dependency and Peer Dependency of Apollo Client to 0.8.0

### PR DESCRIPTION
**Pull request by abhiaiyer91**
TODO:
- [ ] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass
- [ ] Update CHANGELOG.md with your change

### CODE REVIEW

**Comment by abhiaiyer91** [comment]
Sigh why are all these commits here.

**Comment by abhiaiyer91** [comment]
@jbaxleyiii hey dude, somehow i malformed the crap out of this PR. do you think i could just redo this but on a branch on the main project?

**Comment by helfer** [comment]
Thanks @abhiaiyer91 I've fixed this with a separate PR. 🙂

**Comment by abhiaiyer91** [comment]
Hey its the thought that counts :) @helfer thanks Jonas!

**Pull request closed without merging**
