### PR TITLE
Use client store.

### PR DESCRIPTION
**Pull request by amsayk**
Just in case one's using an immutable store.

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
@amsayk could you add these changes to the changelog?

**Comment by amsayk** [comment]
@jbaxleyiii I updated the change log in another pull request #225. Also opened issue #224 to track this. Feel free to close when you merge this.

**Comment by amsayk** [comment]
@jbaxleyiii 

On another subject, it would be great to have react-apollo work out of the box with immutable like redux-form by exposing `react-apollo/immutable`. 

I don't know how feasible it would be or if its best for performance. But if you're open to it, I could send PR.

**Comment by jbaxleyiii** [comment]
@amsayk what are your thoughts on how to accomplish it? I'm open to it for sure!

**Pull request merged**
